let shopItemsData = [
    {
        id: '1',
        name: 'headphone',
        price: 240,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/headphones.jpg',
        typeof: 'new',
        star: 2,
        homManyPeopel: 30,
    },
    {
        id: '2',
        name: 'Shoes',
        price: 60,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/shoes.jpg',
        typeof: 'best seller',
        star: 3,
        homManyPeopel: 530,
    },
    {
        id: '3',
        name: 'Shirt',
        price: 30,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/shirt.jpg',
        typeof: 'unique',
        star: 5,
        homManyPeopel: 20,
    },
    {
        id: '4',
        name: 'Laptop',
        price: 300,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/laptop.webp',
        typeof: 'new',
        star: 5,
        homManyPeopel: 120,
    },
    {
        id: '5',
        name: 'Shoes',
        price: 300,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/shoes2.jpg',
        typeof: 'new',
        star: 4,
        homManyPeopel: 130,
    },
    {
        id: '6',
        name: 'ًWatch',
        price: 100,
        desc: `Lorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidemLorem ipsum dolor sit amet,consectetur adipisicing elit. Fugiat, quidem`,
        img: 'images/watch.webp',
        typeof: 'new',
        star: 2,
        homManyPeopel: 10,
    },
]